services:
  - type: web
    name: xlsx-to-ics-bot
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
    buildCommand: docker build -t xlsx-to-ics-bot .
    startCommand: docker run -p $PORT:8080 xlsx-to-ics-bot
